### ISSUE TITLE
Test classes should be published under scope test

### ISSUE THREAD

**Issue by norrs** [jhannes/action-controller#17]
https://github.com/jhannes/action-controller/tree/master/action-controller/src/main/java/org/fakeservlet seems to belong in scope test.  

Example https://github.com/jhannes/action-controller/blob/master/action-controller/src/main/java/org/fakeservlet/FakeServletResponse.java#L16 pulling in test scope dependency.

**Comment by jhannes** [comment]
Perhaps I should extract org.fakeservlet to a separate module? What do you think, @norrs ?

**Comment by jhannes** [comment]
Thanks for the issue, @norrs. Turns out this oversight had created two bad dependencies from the core of action-controller to assertj. Great to get that resolved!

**Comment by norrs** [comment]
@jhannes I thought this got fixed, but I guess I gave a bit too quick feedback. 

It still pulls in the `fakeservlet` as a transetive dependency ( https://github.com/jhannes/action-controller/blob/master/action-controller/pom.xml#L103 ) where https://github.com/jhannes/action-controller/blob/master/fake-servlet/src/main/java/org/fakeservlet/FakeServletResponse.java#L17 . 

We internally can work around it by excluding fake-servlet and pull it in directly as a test dependency, as I guess the idea is that `fake-servlet` is a test dependency, especially due to the junit import assert.

**Comment by jhannes** [comment]
Whops. That was a mistake. I've pushed a change which will be included in the next release.

Actually, the class FakeApiClient in production scope uses fake servlet. It's very useful to to test your own controllers, but it implements the interface ApiClient, which is also useful for any http-clients. Because of this, I could not make fake-servlet into test-scope for action-controller, but I've now made it optional.
